name: boujee
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.7
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.16.1
  flutter_launcher_icons: ^0.8.1
  flutter_statusbarcolor: ^0.2.3
  google_fonts: ^1.1.1
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  modal_progress_hud: ^0.1.3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
        - asset: assets/fonts/SF-Pro-Rounded-Bold.ttf
          weight: 700
